# Generated by Django 4.2.2 on 2023-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_text_is_fake"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="text_num",
            field=models.IntegerField(default=0),
        ),
    ]
