# Generated by Django 4.2.2 on 2023-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_text_text_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
