# Generated by Django 4.2.2 on 2023-07-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_text_korean_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="root", max_length=500)),
                ("pub_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="score",
            name="choice_text",
        ),
        migrations.RemoveField(
            model_name="score",
            name="votes",
        ),
        migrations.AddField(
            model_name="score",
            name="q1",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="score",
            name="q2",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="score",
            name="q3",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="score",
            name="uploaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="score",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.subject",
            ),
        ),
    ]
